---
title: "Black-Litterman Assignment"
author: "Zhongyun Zhang"
date: "10/15/2020"
output:
  word_document: default
  pdf_document: default
---
```{r}
library("readxl")
library('lubridate')
library('dplyr')
library('zoo')
library('moments')
```


```{r}
data <- read_excel("C:/Users/Zhongyun Zhang/desktop/data.xlsx",
sheet = 1, col_names = TRUE,
col_types = "guess")
```

```{r}
data <-  data[c(-1,-2)]
```




Part 1.
```{r}
covariance <- cov(data) %>% matrix(nrow=3)
eqweights <- c(0.5,0.4,0.1) %>% matrix(nrow = 3)

covariance%*%eqweights
```

```{r}
aversion <- 3
tau <- 0.1

MktVar <- (t(eqweights))%*%(covariance%*%eqweights)

MarketExp.ExcessReturn <- aversion*MktVar
Std.Dev. <- sqrt(MktVar)

ShareRatio <- MarketExp.ExcessReturn/Std.Dev.


prior <- aversion*(covariance%*%eqweights)

adjcov <- tau*covariance

```


Views:
```{r}
ViewP <- c(1,0,0,1,0,-1) %>% matrix(nrow = 2)

ViewQ <- c(0.015,0.03) %>% matrix(nrow = 2)

RelativeConfidence <- 1

tau_omega <- 0.10



Omega <- tau_omega*(ViewP%*%(covariance%*%t(ViewP)))

diagomega <- Omega
diagomega[1,2] <- 0
diagomega[2,1] <- 0


priorconf <- ViewP%*% ((tau*covariance)%*%(t(ViewP)))
```



Posterior Estimates:
```{r}
postret <- prior+((adjcov)%*% ((t(ViewP))%*% (solve(priorconf+Omega))))%*% (ViewQ-(ViewP%*%(prior)))                        


postdist <- covariance +adjcov-(((adjcov)%*%(t(ViewP)))%*%(solve(priorconf+Omega))) %*% (ViewP%*%adjcov)
```



Portfolio Optimization:
```{r}
unconstrained_opt <- t(postret) %*% solve(aversion*postdist)

optweights <- unconstrained_opt/(sum(unconstrained_opt))
```


```{r}
Expected_Return <- t(postret)%*%t(optweights)

Variance <- ((optweights)%*%postdist)%*%(t(optweights))

SD <- sqrt(Variance)
Sharpe_Ratio <- Expected_Return/SD
```

```{r echo=FALSE}
print("For part 1:")

print("The market weights (prior) is:")
print(eqweights %>% as.numeric())
print("for US EQ, Foreign EQ, and Emerging EQ, respectively")

print("The risk aversion parameter is:")
print(aversion)


print("The scalar on the uncertainty in the prior is:")
print(tau)


print("The scalar on manager’s views is:")
print(tau_omega)
```

```{r echo=FALSE}
print("The matrices which capture the manager’s views are:")
print(ViewP)
print(ViewQ)
print(paste("This means that, the manager believes the U.S. equity will earn an excess return of", ViewQ[[1]]*100, "%"))
print(paste("and that, the manager believes that Foreign Equity will outperform Emerging Equity by",ViewQ[[2]]*100, "%"))
```

```{r echo=FALSE}
print("The posterior distribution of returns (expected returns and covariance matrix) are:")
print(postret)
print(postdist)
```

```{r echo=FALSE}
print("The optimal weight in each security is:")
print(optweights)
print("for US Equity, Foreign Equity, and Emerging Equity, respectively")
```
```{r echo=FALSE}
print("After optimization, the expected return is:")
print(Expected_Return %>% as.numeric())
print("Standard deviation is:")
print(SD%>% as.numeric())
print("Sharpe Ratio of the maximum Sharpe Ratio Portfolio is:")
print(Sharpe_Ratio%>% as.numeric())
```






Part 2:
```{r}
covariance <- cov(data) %>% matrix(nrow=3)
eqweights <- c(0.5,0.4,0.1) %>% matrix(nrow = 3)

covariance%*%eqweights
```

```{r}
aversion <- 3
tau <- 0.1

MktVar <- (t(eqweights))%*%(covariance%*%eqweights)

MarketExp.ExcessReturn <- aversion*MktVar
Std.Dev. <- sqrt(MktVar)

ShareRatio <- MarketExp.ExcessReturn/Std.Dev.


prior <- aversion*(covariance%*%eqweights)

adjcov <- tau*covariance

```


Views:
```{r}
ViewP <- c(1,0,0,1,0,-1) %>% matrix(nrow = 2)

ViewQ <- c(0.015,0.03) %>% matrix(nrow = 2)

RelativeConfidence <- 1

tau_omega <- 0.01


Omega <- tau_omega*(ViewP%*%(covariance%*%t(ViewP)))

diagomega <- Omega
diagomega[1,2] <- 0
diagomega[2,1] <- 0


priorconf <- ViewP%*% ((tau*covariance)%*%(t(ViewP)))
```



Posterior Estimates:
```{r}
postret <- prior+((adjcov)%*% ((t(ViewP))%*% (solve(priorconf+Omega))))%*% (ViewQ-(ViewP%*%(prior)))                        


postdist <- covariance +adjcov-(((adjcov)%*%(t(ViewP)))%*%(solve(priorconf+Omega))) %*% (ViewP%*%adjcov)
```



Portfolio Optimization:
```{r}
unconstrained_opt <- t(postret) %*% solve(aversion*postdist)

optweights <- unconstrained_opt/(sum(unconstrained_opt))
```


```{r}
Expected_Return <- t(postret)%*%t(optweights)

Variance <- ((optweights)%*%postdist)%*%(t(optweights))

SD <- sqrt(Variance)
Sharpe_Ratio <- Expected_Return/SD
```

```{r echo=FALSE}
print("For part 2:")

print("The market weights (prior) is:")
print(eqweights %>% as.numeric())
print("for US EQ, Foreign EQ, and Emerging EQ, respectively")

print("The risk aversion parameter is:")
print(aversion)


print("The scalar on the uncertainty in the prior is:")
print(tau)


print("The scalar on manager’s views is:")
print(tau_omega)
```

```{r echo=FALSE}
print("The matrices which capture the manager’s views are:")
print(ViewP)
print(ViewQ)
print(paste("This means that, the manager believes the U.S. equity will earn an excess return of", ViewQ[[1]]*100, "%"))
print(paste("and that, the manager believes that Foreign Equity will outperform Emerging Equity by",ViewQ[[2]]*100, "%"))
```

```{r echo=FALSE}
print("The posterior distribution of returns (expected returns and covariance matrix) are:")
print(postret)
print(postdist)
```

```{r echo=FALSE}
print("The optimal weight in each security is:")
print(optweights)
print("for US Equity, Foreign Equity, and Emerging Equity, respectively")
```
```{r echo=FALSE}
print("After optimization, the expected return is:")
print(Expected_Return %>% as.numeric())
print("Standard deviation is:")
print(SD%>% as.numeric())
print("Sharpe Ratio of the maximum Sharpe Ratio Portfolio is:")
print(Sharpe_Ratio%>% as.numeric())
```






\
\
\
\
\

Part 3:
```{r}
covariance <- cov(data) %>% matrix(nrow=3)
eqweights <- c(0.5,0.4,0.1) %>% matrix(nrow = 3)

covariance%*%eqweights
```

```{r}
aversion <- 3
tau <- 0.1

MktVar <- (t(eqweights))%*%(covariance%*%eqweights)

MarketExp.ExcessReturn <- aversion*MktVar
Std.Dev. <- sqrt(MktVar)

ShareRatio <- MarketExp.ExcessReturn/Std.Dev.


prior <- aversion*(covariance%*%eqweights)

adjcov <- tau*covariance

```


Views:
```{r}
ViewP <- c(0,1,0,-1,1,0) %>% matrix(nrow = 2)

ViewQ <- c(0.015,0.02) %>% matrix(nrow = 2)

tau_omega <- 0.10



Omega <- tau_omega*(ViewP%*%(covariance%*%t(ViewP)))

diagomega <- Omega
diagomega[1,2] <- 0
diagomega[2,1] <- 0


priorconf <- ViewP%*% ((tau*covariance)%*%(t(ViewP)))
```



Posterior Estimates:
```{r}
postret <- prior+((adjcov)%*% ((t(ViewP))%*% (solve(priorconf+Omega))))%*% (ViewQ-(ViewP%*%(prior)))                        


postdist <- covariance +adjcov-(((adjcov)%*%(t(ViewP)))%*%(solve(priorconf+Omega))) %*% (ViewP%*%adjcov)
```



Portfolio Optimization:
```{r}
unconstrained_opt <- t(postret) %*% solve(aversion*postdist)

optweights <- unconstrained_opt/(sum(unconstrained_opt))
```


```{r}
Expected_Return <- t(postret)%*%t(optweights)

Variance <- ((optweights)%*%postdist)%*%(t(optweights))

SD <- sqrt(Variance)
Sharpe_Ratio <- Expected_Return/SD
```

```{r echo=FALSE}
print("For part 3:")

print("The market weights (prior) is:")
print(eqweights %>% as.numeric())
print("for US EQ, Foreign EQ, and Emerging EQ, respectively")

print("The risk aversion parameter is:")
print(aversion)


print("The scalar on the uncertainty in the prior is:")
print(tau)


print("The scalar on manager’s views is:")
print(tau_omega)
```

```{r echo=FALSE}
print("The matrices which capture the manager’s views are:")
print(ViewP)
print(ViewQ)
print(paste("This means that, the manager believes Emerging Equity will earn an excess return of", ViewQ[[1]]*100, "%"))
print(paste("and that, the manager believes that U.S. Equity will outperform Foreign Equity by",ViewQ[[2]]*100, "%"))
```

```{r echo=FALSE}
print("The posterior distribution of returns (expected returns and covariance matrix) are:")
print(postret)
print(postdist)
```

```{r echo=FALSE}
print("The optimal weight in each security is:")
print(optweights)
print("for US Equity, Foreign Equity, and Emerging Equity, respectively")
```

```{r echo=FALSE}
print("After optimization, the expected return is:")
print(Expected_Return %>% as.numeric())
print("Standard deviation is:")
print(SD%>% as.numeric())
print("Sharpe Ratio of the maximum Sharpe Ratio Portfolio is:")
print(Sharpe_Ratio%>% as.numeric())
```